//------------------------------------------------------------------------------
// <auto-generated>
//    이 코드는 템플릿에서 생성되었습니다.
//
//    이 파일을 수동으로 변경하면 응용 프로그램에 예기치 않은 동작이 발생할 수 있습니다.
//    코드가 다시 생성되면 이 파일에 대한 수동 변경 사항을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomePage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articles
    {
        public Articles()
        {
            this.ArticleComments = new HashSet<ArticleComments>();
            this.ArticleFiles = new HashSet<ArticleFiles>();
            this.ArticleCategories = new HashSet<ArticleCategories>();
        }
    
        public int ArticleIDX { get; set; }
        public int BoardIDX { get; set; }
        public string ArticleType { get; set; }
        public string Title { get; set; }
        public string Contents { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string IPAddress { get; set; }
        public Nullable<int> ViewCnt { get; set; }
        public Nullable<System.DateTime> RegistDate { get; set; }
        public string RegistMemberID { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyMemberID { get; set; }
        public string Category { get; set; }
    
        public virtual ICollection<ArticleComments> ArticleComments { get; set; }
        public virtual ICollection<ArticleFiles> ArticleFiles { get; set; }
        public virtual ICollection<ArticleCategories> ArticleCategories { get; set; }
    }
}
